---
TWITTER_CONSUMER_KEY: a1rqHMev2XlWgUK6SWeiOQ
TWITTER_CONSUMER_SECRET: ePR3VRRTUb7GnhBN1mFNIMlVLlE9Z1LpnpiUqg4PA

test:
  INSTAGRAM_CLIENT_ID: 5b6e183568bb46b6bf613bda247ced8d
  INSTAGRAM_CLIENT_SECRET: 97a2401b4a03497ab48f61a9fc078226

  FOURSQUARE_CLIENT_ID: 4QNLF45PWLCTMOGMWUTXW0U3FSACWBIGTKQ2N2MPOKCQW4UU
  FOURSQUARE_CLIENT_SECRET: O3WCBNH4BUTKDUAUXXR2ZCSKOGFZS2IQSJCWSZ3YVCCIWLM0


development:
  INSTAGRAM_CLIENT_ID: 5b6e183568bb46b6bf613bda247ced8d
  INSTAGRAM_CLIENT_SECRET: 97a2401b4a03497ab48f61a9fc078226

  FOURSQUARE_CLIENT_ID: 4QNLF45PWLCTMOGMWUTXW0U3FSACWBIGTKQ2N2MPOKCQW4UU
  FOURSQUARE_CLIENT_SECRET: O3WCBNH4BUTKDUAUXXR2ZCSKOGFZS2IQSJCWSZ3YVCCIWLM0

production:
  INSTAGRAM_CLIENT_ID: f292aeab5d6b4d88822657a1e877ba87
  INSTAGRAM_CLIENT_SECRET: 293325bf2d1a49698e1cccb1a79258d6

  FOURSQUARE_CLIENT_ID: KNC5OQZIYGSRS1MNTD0RZOCJAAKY1O2LZ22FPFE0MMJQUBZR
  FOURSQUARE_CLIENT_SECRET: LDVG0KIIOGOODXWPHD0BQIRKHH1XJ1PDGQZZA53CQLD3F4JN

  RAILS_DB_USR: travlhub
  RAILS_DB_PASS: travlhub


